### PR TITLE
Add confirm alert in button Get people

### PR DESCRIPTION
**Pull request by aabse**
This PR fix the issue https://github.com/rapPayne/edp-people-picker/issues/1

### CODE REVIEW

**Review by rapPayne — CHANGES_REQUESTED** [review]
Nicely done, @aabse! But we can't use confirm() as it is a blocking call. Please use an HTML <dialog> instead. Sorry about that!

**Comment by aabse** [comment]
> Nicely done, @aabse! But we can't use confirm() as it is a blocking call. Please use an HTML instead. Sorry about that!

@rapPayne what do you mean by "blocking call"?

**Comment by rapPayne** [comment]
JavaScript is single-threaded. The main thread will not respond to anything if it is blocked. `alert()`, `prompt()`, and `confirm()` all block that thread. Here's an article that explains more: https://www.telerik.com/blogs/how-to-do-javascript-alerts-without-being-a-jerk

Much better practice: HTML now has a `<dialog>` element. (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog) Use it instead, please.

**Comment by aabse** [comment]
> JavaScript is single-threaded. The main thread will not respond to anything if it is blocked. `alert()`, `prompt()`, and `confirm()` all block that thread. Here's an article that explains more: https://www.telerik.com/blogs/how-to-do-javascript-alerts-without-being-a-jerk
> 
> Much better practice: HTML now has a `<dialog>` element. (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog) Use it instead, please.

Thanks for the explanation! I'll work on that.

**Review by rapPayne — APPROVED** [review]
LGTM. Not sure why you added another dialog instead of using the one that is already there but I can fix that easily enough. I'll clean it up.

**Pull request merged**
